# https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/

credentials:
  usernames:
    navya:
      email: navya@example.com
      name: Navya Barla
      city: Hyderabad
      area: Kukatpally
      role: Admin
      password: '$2b$12$BbvN5RjtRqqBpFNzI4HLS.UNMZF75wc9vJq586FKw9ZZaU/6tJd3u'
cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
    - navya@example.com
